/* AUTOGENERATED by /Users/Shared/gd/good/cache/jenkins/master/eng-mac37/workspace/DAF_on_iOS_KermitMR/common/scripts/buildinfo2src -- DO NOT EDIT */

#ifndef build_info_146842317077_h
#define build_info_146842317077_h

#define BUILDINFO_BUILD_DIR            "/Users/Shared/gd/good/cache/jenkins/master/eng-mac37/workspace/DAF_on_iOS_KermitMR"
#define BUILDINFO_BUILD_TIME           "2016-07-13T15:18:31Z"
#define BUILDINFO_BUILT_BY             "build-gd"
#define BUILDINFO_HOST_NAME            "eng-mac38.local"
#define BUILDINFO_RELEASE_LEVEL        "1"
#define BUILDINFO_RELEASE_SERIAL       "93"
#define BUILDINFO_SRC_REVISION         "v/2.3.0-29-g41917be"
#define BUILDINFO_SRC_URL              "ssh://git@stash.corp.good.com:7999/ge/rel-daf-ios-release.git"
#endif /* build_info_146842317077_h */
