/* AUTOGENERATED by /Users/Shared/gd/good/cache/jenkins/master/eng-mac37/workspace/DAF-on-iOS-Dave/dev/gd/dave-ios/msdk/daf/common/scripts/buildinfo2src -- DO NOT EDIT */

#ifndef build_info_144017635700_h
#define build_info_144017635700_h

#define BUILDINFO_BUILD_DIR            "/Users/Shared/gd/good/cache/jenkins/master/eng-mac37/workspace/DAF-on-iOS-Dave/dev/gd/dave-ios/msdk/daf"
#define BUILDINFO_BUILD_TIME           "2015-08-21T16:58:26Z"
#define BUILDINFO_BUILT_BY             "build-gd"
#define BUILDINFO_HOST_NAME            "ENG-MAC23.local"
#define BUILDINFO_RELEASE_LEVEL        "1"
#define BUILDINFO_RELEASE_SERIAL       "173"
#define BUILDINFO_SRC_REVISION         "v/2.0.0"
#define BUILDINFO_SRC_URL              "p4://perforce-rws2.corp.good.com:3666/depot/dev/gd/dave-ios/msdk/daf"
#endif /* build_info_144017635700_h */
