/* AUTOGENERATED by /jenkins/workspace/Good-Sandbox/GDSDK/DAF.SDK.iOS_Lemondrop_Build.Rel/common/scripts/buildinfo2src -- DO NOT EDIT */

#ifndef build_info_148123717486_h
#define build_info_148123717486_h

#define BUILDINFO_BUILD_DIR            "/jenkins/workspace/Good-Sandbox/GDSDK/DAF.SDK.iOS_Lemondrop_Build.Rel"
#define BUILDINFO_BUILD_TIME           "2016-12-08T22:43:09Z"
#define BUILDINFO_BUILT_BY             "esgbesbuild"
#define BUILDINFO_HOST_NAME            "stgmac-02.devlab2k.testnet.rim.net"
#define BUILDINFO_RELEASE_LEVEL        "1"
#define BUILDINFO_RELEASE_SERIAL       "12"
#define BUILDINFO_SRC_REVISION         "v/3.0.0.0"
#define BUILDINFO_SRC_URL              "ssh://esgbesbuild@stash.corp.good.com:7999/ge/rel-daf-ios-release.git"
#endif /* build_info_148123717486_h */
