   var dependencies = {
    links:
      [
            { "source" : "CoreDetection", "dest" : "Sentegrity_Assertion_Storage" },
            { "source" : "CoreDetection", "dest" : "Sentegrity_Parser" },
            { "source" : "CoreDetection", "dest" : "Sentegrity_TrustFactor_Dispatcher" },
            { "source" : "main", "dest" : "AppDelegate" },
            { "source" : "NSObject+ObjectMap", "dest" : "SOAPObject" },
            { "source" : "Sentegrity_Assertion_Storage", "dest" : "Sentegrity_Assertion_Store" },
            { "source" : "Sentegrity_Assertion_Storage", "dest" : "Sentegrity_Parser" },
            { "source" : "Sentegrity_Parser", "dest" : "DCArrayMapping" },
            { "source" : "Sentegrity_Parser", "dest" : "DCKeyValueObjectMapping" },
            { "source" : "Sentegrity_Parser", "dest" : "DCObjectMapping" },
            { "source" : "Sentegrity_Parser", "dest" : "DCParserConfiguration" },
            { "source" : "Sentegrity_Parser", "dest" : "Sentegrity_Assertion_Store" },
            { "source" : "Sentegrity_Parser", "dest" : "Sentegrity_Classification" },
            { "source" : "Sentegrity_Parser", "dest" : "Sentegrity_DNEModifiers" },
            { "source" : "Sentegrity_Parser", "dest" : "Sentegrity_Policy" },
            { "source" : "Sentegrity_Parser", "dest" : "Sentegrity_Subclassification" },
            { "source" : "Sentegrity_Parser", "dest" : "Sentegrity_TrustFactor" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "Sentegrity_Assertion" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Activity" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Bluetooth" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_CoreDetection" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_File" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Http" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Location" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Netstat" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Platform" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Process" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Route" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Sandbox" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Scan" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Sensor" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Sentegrity" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Subscriber" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Time" },
            { "source" : "Sentegrity_TrustFactor_Dispatcher", "dest" : "TrustFactor_Dispatch_Wifi" },
            { "source" : "TrustFactor_Dispatch_Activity", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Bluetooth", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_CoreDetection", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_File", "dest" : "Sentegrity_Assertion" },
            { "source" : "TrustFactor_Dispatch_File", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Http", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Location", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Netstat", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Platform", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Process", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Route", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Sandbox", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Scan", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Sensor", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Sentegrity", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Subscriber", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Time", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "TrustFactor_Dispatch_Wifi", "dest" : "Sentegrity_TrustFactor_Rule" },
            { "source" : "ViewController", "dest" : "CoreDetection" },
         ]
    }
  ;
